import datetime

class Settings():

    def load(self):
        try:
            settings_file = open("config/settings", "r")
            settings_out = settings_file.readlines()
            data = {}
            for line in settings_out:
                if (line[1] == " "):
                    line = line.replace(":", "").split(" ")
                    data[str(line[1])] = float(line[2])
            settings_file.close()
            return data
        except IOError:
           print("Please insert the settings file!")

    def store(self, data):
        try:
            settings_file = open("config/settings", "w")
            settings_file.write("## File generated by myo_cap software \n"+
                        "## Available from github.com/ddantas/myo_cap \n"+
                        "## Timestamp: "+datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')+" \n"+
                        "##\n"+
                        "## EMG capture settings \n"+
                        "##\n"+
                        "# sampleRate: "+ str(int(data['sampleRate'])) + "\n" + 
                        "# channelsPerBoard: " + str(int(data['channelsPerBoard'])) + "\n" + 
                        "# nBoards: " + str(int(data['nBoards'])) + "\n" +
                        "# bitsPerSample: " + str(data['bitsPerSample']) + "\n" +
                        "# swipeSamples: "+ str(int(data['swipeSamples'])) + "\n"+
                        "# vertTick: " + str(int(data['vertTick'])) + "\n"+ 
                        "# horizTick: " + str(int(data['horizTick'])) + "\n" +
                        "# vMin: " + str(data['vMin']) + "\n"+ 
                        "# vMax: " + str(data['vMax']) + "\n" +
                        "# showChannels: " + str(int(data['showChannels'])))
            settings_file.close()
            return True
        except IOError as err:
            print("ERROR!", err)
            return False
