


#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif


// Constants ////////////////////////////////////////////////////////////////////////////////////////////////

#define Highest_16b_Num        65535       // Highest Value Generated by the for the Function Generator.
#define Highest_12b_Num        4095        // Highest Value Generated by the for the Function Generator.

#define Default_Func_Gen_Freq  10          // The default frequency of the generated signal is 100Hz.

// Function Prototypes //////////////////////////////////////////////////////////////////////////////////////

uint16_t function_gen(uint8_t wave_form_, uint32_t timestamp_, uint32_t func_gen_frequence_);

