# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'propolis_interface.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(808, 476)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lb_titulo = QtGui.QLabel(self.centralwidget)
        self.lb_titulo.setGeometry(QtCore.QRect(350, 40, 760, 24))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.lb_titulo.setFont(font)
        self.lb_titulo.setObjectName(_fromUtf8("lb_titulo"))
        self.rbt_f_be = QtGui.QRadioButton(self.centralwidget)
        self.rbt_f_be.setGeometry(QtCore.QRect(330, 100, 59, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbt_f_be.setFont(font)
        self.rbt_f_be.setAutoExclusive(True)
        self.rbt_f_be.setObjectName(_fromUtf8("rbt_f_be"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.rbt_f_be)
        self.rbt_f_ch = QtGui.QRadioButton(self.centralwidget)
        self.rbt_f_ch.setGeometry(QtCore.QRect(520, 100, 84, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbt_f_ch.setFont(font)
        self.rbt_f_ch.setObjectName(_fromUtf8("rbt_f_ch"))
        self.buttonGroup.addButton(self.rbt_f_ch)
        self.lb_esc_freq = QtGui.QLabel(self.centralwidget)
        self.lb_esc_freq.setGeometry(QtCore.QRect(9, 143, 289, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_esc_freq.setFont(font)
        self.lb_esc_freq.setObjectName(_fromUtf8("lb_esc_freq"))
        self.rbt_f_lp = QtGui.QRadioButton(self.centralwidget)
        self.rbt_f_lp.setGeometry(QtCore.QRect(330, 141, 97, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbt_f_lp.setFont(font)
        self.rbt_f_lp.setObjectName(_fromUtf8("rbt_f_lp"))
        self.buttonGroup_2 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.rbt_f_lp)
        self.rbt_f_hp = QtGui.QRadioButton(self.centralwidget)
        self.rbt_f_hp.setGeometry(QtCore.QRect(435, 140, 88, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbt_f_hp.setFont(font)
        self.rbt_f_hp.setObjectName(_fromUtf8("rbt_f_hp"))
        self.buttonGroup_2.addButton(self.rbt_f_hp)
        self.rbt_f_bp = QtGui.QRadioButton(self.centralwidget)
        self.rbt_f_bp.setGeometry(QtCore.QRect(532, 140, 88, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbt_f_bp.setFont(font)
        self.rbt_f_bp.setObjectName(_fromUtf8("rbt_f_bp"))
        self.buttonGroup_2.addButton(self.rbt_f_bp)
        self.rbt_f_bs = QtGui.QRadioButton(self.centralwidget)
        self.rbt_f_bs.setGeometry(QtCore.QRect(630, 140, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbt_f_bs.setFont(font)
        self.rbt_f_bs.setObjectName(_fromUtf8("rbt_f_bs"))
        self.buttonGroup_2.addButton(self.rbt_f_bs)
        self.bt_init_conv = QtGui.QPushButton(self.centralwidget)
        self.bt_init_conv.setGeometry(QtCore.QRect(179, 360, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_init_conv.setFont(font)
        self.bt_init_conv.setObjectName(_fromUtf8("bt_init_conv"))
        self.lb_fc = QtGui.QLabel(self.centralwidget)
        self.lb_fc.setGeometry(QtCore.QRect(10, 186, 134, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_fc.setFont(font)
        self.lb_fc.setObjectName(_fromUtf8("lb_fc"))
        self.lineEdit_fc = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_fc.setGeometry(QtCore.QRect(207, 188, 133, 20))
        self.lineEdit_fc.setObjectName(_fromUtf8("lineEdit_fc"))
        self.lb_HZ = QtGui.QLabel(self.centralwidget)
        self.lb_HZ.setGeometry(QtCore.QRect(346, 188, 18, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_HZ.setFont(font)
        self.lb_HZ.setObjectName(_fromUtf8("lb_HZ"))
        self.lb_fa = QtGui.QLabel(self.centralwidget)
        self.lb_fa.setGeometry(QtCore.QRect(9, 268, 184, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_fa.setFont(font)
        self.lb_fa.setObjectName(_fromUtf8("lb_fa"))
        self.lineEdit_fa = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_fa.setGeometry(QtCore.QRect(207, 268, 133, 20))
        self.lineEdit_fa.setObjectName(_fromUtf8("lineEdit_fa"))
        self.lb_HZ_3 = QtGui.QLabel(self.centralwidget)
        self.lb_HZ_3.setGeometry(QtCore.QRect(346, 268, 18, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_HZ_3.setFont(font)
        self.lb_HZ_3.setObjectName(_fromUtf8("lb_HZ_3"))
        self.bt_stop_conv = QtGui.QPushButton(self.centralwidget)
        self.bt_stop_conv.setGeometry(QtCore.QRect(382, 360, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_stop_conv.setFont(font)
        self.bt_stop_conv.setObjectName(_fromUtf8("bt_stop_conv"))
        self.lb_esc_filtro = QtGui.QLabel(self.centralwidget)
        self.lb_esc_filtro.setGeometry(QtCore.QRect(9, 101, 202, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_esc_filtro.setFont(font)
        self.lb_esc_filtro.setObjectName(_fromUtf8("lb_esc_filtro"))
        self.rbt_f_bu = QtGui.QRadioButton(self.centralwidget)
        self.rbt_f_bu.setGeometry(QtCore.QRect(410, 100, 86, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbt_f_bu.setFont(font)
        self.rbt_f_bu.setObjectName(_fromUtf8("rbt_f_bu"))
        self.buttonGroup.addButton(self.rbt_f_bu)
        self.lineEdit_fc_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_fc_2.setGeometry(QtCore.QRect(207, 230, 133, 20))
        self.lineEdit_fc_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_fc_2.setObjectName(_fromUtf8("lineEdit_fc_2"))
        self.lb_HZ_2 = QtGui.QLabel(self.centralwidget)
        self.lb_HZ_2.setGeometry(QtCore.QRect(346, 230, 18, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_HZ_2.setFont(font)
        self.lb_HZ_2.setObjectName(_fromUtf8("lb_HZ_2"))
        self.lb_fc_2 = QtGui.QLabel(self.centralwidget)
        self.lb_fc_2.setGeometry(QtCore.QRect(10, 229, 147, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_fc_2.setFont(font)
        self.lb_fc_2.setObjectName(_fromUtf8("lb_fc_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 230, 269, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.lb_ripple = QtGui.QLabel(self.centralwidget)
        self.lb_ripple.setGeometry(QtCore.QRect(11, 301, 109, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_ripple.setFont(font)
        self.lb_ripple.setObjectName(_fromUtf8("lb_ripple"))
        self.lineEdit_chebrip = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_chebrip.setGeometry(QtCore.QRect(209, 301, 133, 20))
        self.lineEdit_chebrip.setObjectName(_fromUtf8("lineEdit_chebrip"))
        self.lb_ordem = QtGui.QLabel(self.centralwidget)
        self.lb_ordem.setGeometry(QtCore.QRect(10, 331, 50, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_ordem.setFont(font)
        self.lb_ordem.setObjectName(_fromUtf8("lb_ordem"))
        self.lineEdit_ordem = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_ordem.setGeometry(QtCore.QRect(207, 331, 133, 20))
        self.lineEdit_ordem.setObjectName(_fromUtf8("lineEdit_ordem"))
        self.rbt_gerador_sim = QtGui.QRadioButton(self.centralwidget)
        self.rbt_gerador_sim.setGeometry(QtCore.QRect(521, 233, 49, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rbt_gerador_sim.setFont(font)
        self.rbt_gerador_sim.setObjectName(_fromUtf8("rbt_gerador_sim"))
        self.buttonGroup_3 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName(_fromUtf8("buttonGroup_3"))
        self.buttonGroup_3.addButton(self.rbt_gerador_sim)
        self.rbt_gerador_nao = QtGui.QRadioButton(self.centralwidget)
        self.rbt_gerador_nao.setGeometry(QtCore.QRect(576, 233, 53, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rbt_gerador_nao.setFont(font)
        self.rbt_gerador_nao.setObjectName(_fromUtf8("rbt_gerador_nao"))
        self.buttonGroup_3.addButton(self.rbt_gerador_nao)
        self.lb_gerador = QtGui.QLabel(self.centralwidget)
        self.lb_gerador.setGeometry(QtCore.QRect(445, 211, 300, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_gerador.setFont(font)
        self.lb_gerador.setObjectName(_fromUtf8("lb_gerador"))
        self.lineEdit_freq_ger = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_freq_ger.setGeometry(QtCore.QRect(585, 275, 133, 20))
        self.lineEdit_freq_ger.setObjectName(_fromUtf8("lineEdit_freq_ger"))
        self.lb_freq_sinal_ger = QtGui.QLabel(self.centralwidget)
        self.lb_freq_sinal_ger.setGeometry(QtCore.QRect(476, 275, 103, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lb_freq_sinal_ger.setFont(font)
        self.lb_freq_sinal_ger.setObjectName(_fromUtf8("lb_freq_sinal_ger"))
        self.rbt_f_bu.raise_()
        self.lb_titulo.raise_()
        self.rbt_f_be.raise_()
        self.rbt_f_ch.raise_()
        self.lb_esc_filtro.raise_()
        self.lb_esc_freq.raise_()
        self.rbt_f_lp.raise_()
        self.rbt_f_hp.raise_()
        self.rbt_f_bp.raise_()
        self.rbt_f_bs.raise_()
        self.bt_init_conv.raise_()
        self.lb_fc.raise_()
        self.lineEdit_fc.raise_()
        self.lb_HZ.raise_()
        self.lb_fa.raise_()
        self.lineEdit_fa.raise_()
        self.lb_HZ_3.raise_()
        self.bt_stop_conv.raise_()
        self.lineEdit_fc_2.raise_()
        self.lb_HZ_2.raise_()
        self.lb_fc_2.raise_()
        self.label.raise_()
        self.lb_ripple.raise_()
        self.lineEdit_chebrip.raise_()
        self.lb_ordem.raise_()
        self.lineEdit_ordem.raise_()
        self.rbt_gerador_sim.raise_()
        self.rbt_gerador_nao.raise_()
        self.lb_gerador.raise_()
        self.lineEdit_freq_ger.raise_()
        self.lb_freq_sinal_ger.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.rbt_f_bu, self.rbt_f_lp)
        MainWindow.setTabOrder(self.rbt_f_lp, self.rbt_f_hp)
        MainWindow.setTabOrder(self.rbt_f_hp, self.rbt_f_bp)
        MainWindow.setTabOrder(self.rbt_f_bp, self.rbt_f_bs)
        MainWindow.setTabOrder(self.rbt_f_bs, self.rbt_f_be)
        MainWindow.setTabOrder(self.rbt_f_be, self.bt_init_conv)
        MainWindow.setTabOrder(self.bt_init_conv, self.lineEdit_fc)
        MainWindow.setTabOrder(self.lineEdit_fc, self.lineEdit_fa)
        MainWindow.setTabOrder(self.lineEdit_fa, self.bt_stop_conv)
        MainWindow.setTabOrder(self.bt_stop_conv, self.rbt_f_ch)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.lb_titulo.setText(_translate("MainWindow", "ProDIS", None))
        self.rbt_f_be.setText(_translate("MainWindow", "Bessel", None))
        self.rbt_f_ch.setText(_translate("MainWindow", "Chebyshev", None))
        self.lb_esc_freq.setText(_translate("MainWindow", "Escolha a resposta em frequência desejada:", None))
        self.rbt_f_lp.setText(_translate("MainWindow", "Passa-baixas", None))
        self.rbt_f_hp.setText(_translate("MainWindow", "Passa-altas", None))
        self.rbt_f_bp.setText(_translate("MainWindow", "Passa-faixa", None))
        self.rbt_f_bs.setText(_translate("MainWindow", "Rejeita-faixa", None))
        self.bt_init_conv.setText(_translate("MainWindow", "Iniciar Conversão", None))
        self.lb_fc.setText(_translate("MainWindow", "Frequência de corte:", None))
        self.lb_HZ.setText(_translate("MainWindow", "HZ", None))
        self.lb_fa.setText(_translate("MainWindow", "Frequência de amostragem:", None))
        self.lb_HZ_3.setText(_translate("MainWindow", "HZ", None))
        self.bt_stop_conv.setText(_translate("MainWindow", "Parar Conversão", None))
        self.lb_esc_filtro.setText(_translate("MainWindow", "Escolha o filtro digital desejado:", None))
        self.rbt_f_bu.setText(_translate("MainWindow", "Butterworth", None))
        self.lb_HZ_2.setText(_translate("MainWindow", "HZ", None))
        self.lb_fc_2.setText(_translate("MainWindow", "Frequência de corte 2:", None))
        self.lb_ripple.setText(_translate("MainWindow", "Ripple da Banda:", None))
        self.lb_ordem.setText(_translate("MainWindow", "Ordem:", None))
        self.rbt_gerador_sim.setText(_translate("MainWindow", "Sim", None))
        self.rbt_gerador_nao.setText(_translate("MainWindow", "Não", None))
        self.lb_gerador.setText(_translate("MainWindow", "Usar Gerador de Sinal como Entrada?", None))
        self.lb_freq_sinal_ger.setText(_translate("MainWindow", "Frequência Sinal", None))

