
// Includes

#include <stdint.h>

#ifndef M_PI
#    define M_PI 3.14159265358979323846
#endif


// Constants

#define Highest_16b_Num        65535       // Highest Value Generated by the for the Function Generator.
#define Highest_12b_Num        4095        // Highest Value Generated by the for the Function Generator.

#define Default_Func_Gen_Freq  100          // The default frequency of the generated signal is 500Hz.

#define ADC_Acquisition        0           // ADC Acquisition Mode.
#define Sine_Wave              1           // Type of Waveform that can be used by the Function Generator.
#define Square_Wave            2           // Type of Waveform that can be used by the Function Generator.
#define Sawtooth_Wave          3           // Type of Waveform that can be used by the Function Generator.


//Function Prototype.

uint16_t function_gen(uint8_t wave_form_, uint32_t timestamp_, uint32_t func_gen_frequence_);

